### ISSUE TITLE
Add slashcmd to reset data

### ISSUE THREAD

**Issue by QuadrozZz** [shagu/ShaguDPS#6]
Please can you add hotkey or slash command for data reset (without confirmation). Both would be better:)

**Comment by shagu** [comment]
What's wrong with shift-clicking it?

**Comment by QuadrozZz** [comment]
Nothing, its working very fine. But would be very good combine with macro /sd toggle.

**Comment by QuadrozZz** [comment]
And if the addon remembers the visible settings the next time you login/reload, it would also be nice.

It is not very important things, but makes some qol better ;) Also if it is not hard, ofc.

**Comment by shagu** [comment]
It remembers the visible settings. But I assume you are using pfUI which hides the DPS docking frame by default: /pfUI -> Thirdparty -> Show Meters By Default [x].
Or you could disable the ShaguDPS (Dock) in the pfUI settings if you prefer to not have it docked.
