### ISSUE TITLE
"resisted" messages are interpreted as part of spell name

### ISSUE THREAD

**Issue by wodim** [shagu/ShaguDPS#7]
Better explained with a screenshot:

![image](https://github.com/shagu/ShaguDPS/assets/1001553/44a67076-933c-4b4c-82fe-702d3324f3fe)

Also happens with absorbs.

**Comment by shagu** [comment]
https://github.com/shagu/ShaguDPS/commit/493f34ffdd7e6731b1443f4e8ea0e640cd274767
